### ISSUE TITLE
New ramtest give wrong number of RAM and doesn't see the 4MB memory expansion.

### ISSUE THREAD

**Issue by nbrok** [rosco-m68k/rosco_m68k#135]
![Schermafbeelding_2020-10-05_om_17 37 05](https://user-images.githubusercontent.com/40683681/95118739-16b78680-074b-11eb-8261-1509c6b85aa6.png)
![Schermafbeelding_2020-10-05_om_17 38 08](https://user-images.githubusercontent.com/40683681/95118777-246d0c00-074b-11eb-94cd-5877874a4c54.png)

**Comment by roscopeco** [comment]
Theory: This issue may be caused by the recent changes to move the stack into expansion RAM (if present). Memcheck does destructive testing of everything above the 1MB mark so will be overwriting the stack.
