### ISSUE TITLE
Firmware seems not recognise expanded RAM correctly fix-sd-write  branch

### ISSUE THREAD

**Issue by nbrok** [rosco-m68k/rosco_m68k#142]
Did you change something? I peeked in the code (firmware) and _SDB_MEM_SIZE ($414) seems the real end of memory value. The value on $0 gives the top of internal RAM. Xarks sdfat_menu uses the INITIAL_STACK value to determine the size of memory.

**Comment by roscopeco** [comment]
We are not setting the initial stack vector at the same time as the warm boot vector is set up. We should do that.
