### ISSUE TITLE
Some manufacturing questions

### ISSUE THREAD

**Issue by GBeushausen** [rosco-m68k/rosco_m68k#331]
I'm trying to produce the boards with PCBWay. They have two questions, which i don't know what it means.

1. For 4 layer board, we will make both inner and outer copper thickness 1/1oz, is it ok?
2. You noted RoHS in the file, but selected HASL with lead surface treatment cannot fit, pls advise.

What should i choose? Can i choose HASL?

**Comment by roscopeco** [comment]
1. Yes that will be fine.
2. If the boards are for yourself and you don’t mind lead, you can go with Leaded HASL if you like. If you want to be kinder to the environment you can choose lead-free HASL. They are only asking because the leaded HASL is not RoHS compliant.

**Comment by roscopeco** [comment]
I'm going to assume this answered your questions. Closing.
