### ISSUE TITLE
Proposed board alterations: Breakout EXPSEL in J6 and add optional DIP16 oscillator footprint

### ISSUE THREAD

**Issue by HeathenUK** [rosco-m68k/rosco_m68k#333]
As requested, just jotting down two thoughts on potential improvements:

- At the moment EXPSEL is only broken out via J3, where adding it to J6 would make it possible to create expansion RAM hat PCBs that don't require IC2 to be customised where one doesn't want to use the J3 connector (for example, if you explicitly only want to use it for Xosera and don't want a backplane).
- For whatever reason DIP8 oscillators are getting rarer while DIP14 are still freely available. It looks like there's sufficient board space to add optional DIP14-compatible pins (similar to the way we accommodate either size of cap for the DUART crystal.

**Comment by roscopeco** [comment]
Thanks for this @HeathenUK , and apologies for the delay in getting to it. I have raised a PR that will address `EXPSEL` (adding it to `J6` as you suggest). On this board revision I have decided not to do the `Q2` resize / additional pins, but will keep it in mind for a future bigger respin / the next version :)
